In [1]:
# task 1 is the  lexicon
# Lexicon is a collection of words/Phrases + Information (POS; tense Definitions..)
# Lexicon has lexical entries -> each entry is Word/Phrase -> has a HeadWord(Lemma) + Information

In [2]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [3]:
import nltk
entries= nltk.corpus.cmudict.entries()
len(entries)

133737

In [4]:
entries[:100]

[('a', ['AH0']),
 ('a.', ['EY1']),
 ('a', ['EY1']),
 ('a42128',
  ['EY1',
   'F',
   'AO1',
   'R',
   'T',
   'UW1',
   'W',
   'AH1',
   'N',
   'T',
   'UW1',
   'EY1',
   'T']),
 ('aaa', ['T', 'R', 'IH2', 'P', 'AH0', 'L', 'EY1']),
 ('aaberg', ['AA1', 'B', 'ER0', 'G']),
 ('aachen', ['AA1', 'K', 'AH0', 'N']),
 ('aachener', ['AA1', 'K', 'AH0', 'N', 'ER0']),
 ('aaker', ['AA1', 'K', 'ER0']),
 ('aalseth', ['AA1', 'L', 'S', 'EH0', 'TH']),
 ('aamodt', ['AA1', 'M', 'AH0', 'T']),
 ('aancor', ['AA1', 'N', 'K', 'AO2', 'R']),
 ('aardema', ['AA0', 'R', 'D', 'EH1', 'M', 'AH0']),
 ('aardvark', ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K']),
 ('aaron', ['EH1', 'R', 'AH0', 'N']),
 ("aaron's", ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aarons', ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aaronson', ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ('aaronson', ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ("aaronson's", ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z']),
 ("aaronson's", ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z'

In [5]:
#3. Wordnet
from nltk.corpus import wordnet as wn
wn.synsets('bike')

[Synset('motorcycle.n.01'), Synset('bicycle.n.01'), Synset('bicycle.v.01')]

In [6]:
wn.synset('bike.n.01').lemma_names()

['motorcycle', 'bike']

In [7]:
#Task 2 - SIMPLE TEXT CLASSIFIER
def gender_features(word):
    return {'last_letter':word[-1]}

In [8]:
gender_features('Vernit')

{'last_letter': 't'}

In [9]:
from nltk.corpus import names
labeled_names = ([(name,'male') for name in names.words('male.txt')] + [(name,'female') for name in names.words('female.txt')])

In [10]:
import random
random.shuffle(labeled_names)

In [11]:
featuresets = [(gender_features(n),gender) for (n,gender) in labeled_names]

In [12]:
train_set,test_test = featuresets[500:],featuresets[:500]

In [13]:
import nltk
classifier = nltk.NaiveBayesClassifier.train(train_set)

In [14]:
classifier.classify(gender_features('Vernit'))

'male'

In [15]:
classifier.classify(gender_features('Sachin'))

'male'

In [16]:
classifier.classify(gender_features('India'))

'female'

In [17]:
classifier.classify(gender_features('House'))

'female'

In [18]:
print(nltk.classify.accuracy(classifier,test_test))

0.778


In [19]:
#Vectorizers & Cosine Similarity
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
vect = CountVectorizer(binary=True)
corpus=["PCA is good for feature extraction","feature extraction is necessary for classification tasks"]
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [21]:
vocab=vect.vocabulary_

In [22]:
for key in sorted(vocab.keys()):
    print("{}:{}".format(key,vocab[key]))

classification:0
extraction:1
feature:2
for:3
good:4
is:5
necessary:6
pca:7
tasks:8


In [23]:
print(vect.transform(["Machine Learning tasks!!"]).toarray())

[[0 0 0 0 0 0 0 0 1]]


In [24]:
print(vect.transform(corpus).toarray())

[[0 1 1 1 1 1 0 1 0]
 [1 1 1 1 0 1 1 0 1]]


In [25]:
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
similarity = cosine_similarity(vect.transform(["Google Cloud Vision is a character recognition engine"]).toarray(), vect.transform(["OCR is an optical character recognition engine"]).toarray())

In [27]:
similarity[0][0]

1.0